2024-11-10 16:27:44,480 : INFO : root : Loading config.
2024-11-10 16:27:44,482 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-11-10 16:27:44,482 : WARNING : ConfigProcessor : Config file in cache changed: C:\git\pinball-at-nx\source\mpf-conda\config\config.yaml
2024-11-10 16:27:44,482 : INFO : ConfigProcessor : Loading config from file C:\Users\eliri\anaconda3\Lib\site-packages\mpf\mpfconfig.yaml.
2024-11-10 16:27:44,488 : INFO : ConfigProcessor : Loading config: C:\Users\eliri\anaconda3\Lib\site-packages\mpf\mpfconfig.yaml
2024-11-10 16:27:44,489 : INFO : ConfigProcessor : Loading config from file C:\git\pinball-at-nx\source\mpf-conda\config\config.yaml.
2024-11-10 16:27:44,490 : INFO : ConfigProcessor : Loading config: C:\git\pinball-at-nx\source\mpf-conda\config\config.yaml
2024-11-10 16:27:44,491 : INFO : ConfigProcessor : Config file cache created: C:\Users\eliri\AppData\Local\Temp\832545c8267d39f841337814b695fcbf.mpf_cache
2024-11-10 16:27:44,536 : INFO : ConfigProcessor : Loading config from cache: C:\Users\eliri\AppData\Local\Temp\752f721450cdb51a7adcb1ccc9eded7a.mpf_cache
2024-11-10 16:27:44,537 : INFO : ConfigProcessor : Loading config from cache: C:\Users\eliri\AppData\Local\Temp\d7fa13d75974d3198a20ad67f567c1d5.mpf_cache
2024-11-10 16:27:44,537 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev5
2024-11-10 16:27:44,537 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2024-11-10-16-27-44-mpf-YogEr.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': 'C:\\git\\pinball-at-nx\\source\\mpf-conda\\logs\\2024-11-10-16-27-44-mpf-YogEr.log'}
2024-11-10 16:27:44,537 : INFO : Machine : MPF path: C:\Users\eliri\anaconda3\Lib\site-packages\mpf
2024-11-10 16:27:44,537 : INFO : Machine : Machine path: C:\git\pinball-at-nx\source\mpf-conda
2024-11-10 16:27:44,537 : INFO : Machine : Platform: win32
2024-11-10 16:27:44,537 : INFO : Machine : Python executable location: C:\Users\eliri\anaconda3\python.exe
2024-11-10 16:27:44,537 : INFO : Machine : Python version: 3.12.7 (64-bit)
2024-11-10 16:27:44,539 : INFO : Machine : Initializing MPF...
2024-11-10 16:27:44,549 : ERROR : Machine : Failed to initialize MPF
Traceback (most recent call last):
  File "C:\Users\eliri\anaconda3\Lib\site-packages\mpf\core\machine.py", line 686, in initialize_mpf
    raise init.exception()
  File "C:\Users\eliri\anaconda3\Lib\site-packages\mpf\core\machine.py", line 248, in initialize
    await self.initialize_core_and_hardware()
  File "C:\Users\eliri\anaconda3\Lib\site-packages\mpf\core\machine.py", line 234, in initialize_core_and_hardware
    self._load_hardware_platforms()
  File "C:\Users\eliri\anaconda3\Lib\site-packages\mpf\core\machine.py", line 490, in _load_hardware_platforms
    self.add_platform(hardware_platform)
  File "C:\Users\eliri\anaconda3\Lib\site-packages\mpf\core\machine.py", line 620, in add_platform
    self.hardware_platforms[name] = hardware_platform(self)
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eliri\anaconda3\Lib\site-packages\mpf\platforms\opp\opp.py", line 78, in __init__
    self.config = self.machine.config_validator.validate_config("opp", self.machine.config.get('opp', {}))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eliri\anaconda3\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eliri\anaconda3\Lib\site-packages\mpf\core\config_validator.py", line 214, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eliri\anaconda3\Lib\site-packages\mpf\core\config_validator.py", line 236, in validate_config_item
    raise self.validation_error(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry opp:opp:ports = "None" is not valid. Required setting "ports:" is missing from section "opp:opp:" in your config. Error Code: CFE-ConfigValidator-9 (https://missionpinball.org/logs)
2024-11-10 16:27:47,079 : INFO : root : MPF run loop ended.
